name = "Cogs & Quests"
author = "Runar & Mjolner"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f4c50e78bd0b6ed24a912cc4cffa71c405169f3936087cd35d6c2b83c4efb2e"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
