name = "Cogs & Quests"
author = "Runar & Mjolner"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13adde203aec31e3b08ceb2d8ce525a062959f2da7ee474f259c247365d88c76"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
