name = "Cogs & Quests"
author = "Runar & Mjolner"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b965df315e989b35e6eeb5c3720758480b37f6564a658a95816bef6cb589c4f4"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
